-- Garment & accessory category tags (180 tags from CSV batches 2–10)

insert into public.tags (category, label, slug, reach_tier, relevance_contexts, sort_order)
values
  ('Robes', 'Robe2026', 'robe2026', 'Moyen', array['lookbook','quotidien'], 201),
  ('Robes', 'RobeFemme', 'robefemme', 'Élevé', array['lookbook','quotidien'], 202),
  ('Robes', 'RobeMidi', 'robemidi', 'Moyen', array['lookbook','quotidien'], 203),
  ('Robes', 'RobeLongue', 'robelongue', 'Moyen', array['lookbook','quotidien'], 204),
  ('Robes', 'RobeCourte', 'robecourte', 'Moyen', array['lookbook','quotidien'], 205),
  ('Robes', 'RobeSatinée', 'robesatinee', 'Moyen', array['lookbook','défilé'], 206),
  ('Robes', 'RobeDosNu', 'robedosnu', 'Moyen', array['lookbook','soirée'], 207),
  ('Robes', 'RobePortefeuille', 'robeportefeuille', 'Moyen', array['quotidien','bureau'], 208),
  ('Robes', 'RobeBustier', 'robebustier', 'Moyen', array['soirée','lookbook'], 209),
  ('Robes', 'RobeColBateau', 'robecolbateau', 'Faible à moyen', array['lookbook','quotidien'], 210),
  ('Robes', 'RobeImprimée', 'robeimprimee', 'Moyen', array['lookbook','quotidien'], 211),
  ('Robes', 'RobeFleurie', 'robefleurie', 'Élevé', array['lookbook','quotidien'], 212),
  ('Robes', 'RobeNoire', 'robenoire', 'Élevé', array['soirée','lookbook'], 213),
  ('Robes', 'RobeBlanche', 'robeblanche', 'Élevé', array['évènement','lookbook'], 214),
  ('Robes', 'RobeDeSoirée', 'robedesoiree', 'Élevé', array['défilé','évènement'], 215),
  ('Robes', 'RobeDeJour', 'robedejour', 'Moyen', array['quotidien'], 216),
  ('Robes', 'SlipDress', 'slipdress', 'Moyen', array['lookbook','soirée'], 217),
  ('Robes', 'RobeEnDentelle', 'robeendentelle', 'Moyen', array['évènement','lookbook'], 218),
  ('Robes', 'RobeTailleEmpire', 'robetailleempire', 'Faible à moyen', array['lookbook','quotidien'], 219),
  ('Robes', 'RobePlissée', 'robeplissee', 'Moyen', array['lookbook','quotidien'], 220),
  ('Tops', 'TopFemme', 'topfemme', 'Élevé', array['lookbook','quotidien'], 221),
  ('Tops', 'TopSatin', 'topsatin', 'Moyen', array['soirée','lookbook'], 222),
  ('Tops', 'TopDosNu', 'topdosnu', 'Moyen', array['soirée','été'], 223),
  ('Tops', 'CropTopFemme', 'croptopfemme', 'Élevé', array['quotidien','TikTok'], 224),
  ('Tops', 'ChemiseOversize', 'chemiseoversize', 'Moyen', array['lookbook','quotidien'], 225),
  ('Tops', 'ChemiseBlanche', 'chemiseblanche', 'Élevé', array['bureau','lookbook'], 226),
  ('Tops', 'BodyFemme', 'bodyfemme', 'Moyen', array['lookbook','quotidien'], 227),
  ('Tops', 'CaracoSatin', 'caracosatin', 'Moyen', array['soirée','lookbook'], 228),
  ('Tops', 'TopBandeau', 'topbandeau', 'Moyen', array['été','festival'], 229),
  ('Tops', 'TopAsymétrique', 'topasymetrique', 'Faible à moyen', array['lookbook','défilé'], 230),
  ('Tops', 'ChemiseRayée', 'chemiserayee', 'Moyen', array['bureau','quotidien'], 231),
  ('Tops', 'TopTransparent', 'toptransparent', 'Moyen', array['soirée','lookbook'], 232),
  ('Tops', 'TopSecondeMain', 'topsecondemain', 'Faible à moyen', array['quotidien','sustainable'], 233),
  ('Tops', 'ChemiseVintage', 'chemisevintage', 'Moyen', array['vintage','quotidien'], 234),
  ('Tops', 'TopMaille', 'topmaille', 'Moyen', array['automne','quotidien'], 235),
  ('Tops', 'TopColRoulé', 'topcolroule', 'Moyen', array['hiver','quotidien'], 236),
  ('Tops', 'ChemiseEnJean', 'chemiseenjean', 'Moyen', array['casual','quotidien'], 237),
  ('Tops', 'TopBasique', 'topbasique', 'Moyen', array['quotidien','capsule wardrobe'], 238),
  ('Tops', 'TopY2K', 'topy2k', 'Moyen', array['TikTok','lookbook'], 239),
  ('Tops', 'TopCoquette', 'topcoquette', 'Faible à moyen', array['niche','lookbook'], 240),
  ('Pantalons', 'PantalonFemme', 'pantalonfemme', 'Élevé', array['lookbook','quotidien'], 241),
  ('Pantalons', 'PantalonLarge', 'pantalonlarge', 'Élevé', array['lookbook','quotidien'], 242),
  ('Pantalons', 'PantalonTailleurFemme', 'pantalontailleurfemme', 'Moyen', array['bureau','lookbook'], 243),
  ('Pantalons', 'PantalonCargo', 'pantaloncargo', 'Élevé', array['streetstyle','TikTok'], 244),
  ('Pantalons', 'PantalonParachute', 'pantalonparachute', 'Moyen', array['streetstyle','niche'], 245),
  ('Pantalons', 'PantalonFluide', 'pantalonfluide', 'Moyen', array['quotidien','été'], 246),
  ('Pantalons', 'PantalonPlissé', 'pantalonplisse', 'Faible à moyen', array['lookbook','quotidien'], 247),
  ('Pantalons', 'PantalonEnCuir', 'pantalonencuir', 'Moyen', array['soirée','lookbook'], 248),
  ('Pantalons', 'LeggingStyle', 'leggingstyle', 'Élevé', array['sport','athleisure'], 249),
  ('Pantalons', 'CyclisteFemme', 'cyclistefemme', 'Moyen', array['streetstyle','été'], 250),
  ('Jeans', 'JeanFemme', 'jeanfemme', 'Élevé', array['lookbook','quotidien'], 251),
  ('Jeans', 'JeanBaggyFemme', 'jeanbaggyfemme', 'Élevé', array['streetstyle','TikTok'], 252),
  ('Jeans', 'JeanLargeFemme', 'jeanlargefemme', 'Élevé', array['lookbook','quotidien'], 253),
  ('Jeans', 'JeanStraight', 'jeanstraight', 'Moyen', array['quotidien'], 254),
  ('Jeans', 'JeanMom', 'jeanmom', 'Moyen', array['quotidien','vintage'], 255),
  ('Jeans', 'JeanVintageFemme', 'jeanvintagefemme', 'Moyen', array['seconde main'], 256),
  ('Jeans', 'JeanTailleHaute', 'jeantaillehaute', 'Élevé', array['lookbook','quotidien'], 257),
  ('Jeans', 'JeanBlanc', 'jeanblanc', 'Moyen', array['été','lookbook'], 258),
  ('Jeans', 'JeanNoir', 'jeannoir', 'Élevé', array['quotidien','soirée'], 259),
  ('Jeans', 'JeanPatchwork', 'jeanpatchwork', 'Faible à moyen', array['niche','éditorial'], 260),
  ('Jupes', 'JupeFemme', 'jupefemme', 'Élevé', array['lookbook','quotidien'], 261),
  ('Jupes', 'JupeMidi', 'jupemidi', 'Moyen', array['lookbook','quotidien'], 262),
  ('Jupes', 'JupeLongue', 'jupelongue', 'Moyen', array['lookbook','quotidien'], 263),
  ('Jupes', 'JupeCourte', 'jupecourte', 'Moyen', array['lookbook','quotidien'], 264),
  ('Jupes', 'JupePlissée', 'jupeplissee', 'Élevé', array['lookbook','bureau'], 265),
  ('Jupes', 'JupeJeans', 'jupejeans', 'Moyen', array['casual','quotidien'], 266),
  ('Jupes', 'JupeCrayon', 'jupecrayon', 'Moyen', array['bureau','évènement'], 267),
  ('Jupes', 'MiniJupe', 'minijupe', 'Élevé', array['TikTok','lookbook'], 268),
  ('Jupes', 'JupePortefeuille', 'jupeportefeuille', 'Moyen', array['quotidien','lookbook'], 269),
  ('Jupes', 'JupeSatin', 'jupesatin', 'Moyen', array['soirée','lookbook'], 270),
  ('Shorts', 'ShortFemme', 'shortfemme', 'Élevé', array['été','quotidien'], 271),
  ('Shorts', 'ShortTailleur', 'shorttailleur', 'Moyen', array['bureau','lookbook'], 272),
  ('Shorts', 'ShortEnJean', 'shortenjean', 'Élevé', array['été','casual'], 273),
  ('Shorts', 'ShortBermuda', 'shortbermuda', 'Moyen', array['streetstyle','lookbook'], 274),
  ('Shorts', 'ShortParachute', 'shortparachute', 'Faible à moyen', array['niche','TikTok'], 275),
  ('Shorts', 'ShortVintage', 'shortvintage', 'Faible à moyen', array['seconde main'], 276),
  ('Shorts', 'CyclisteNoir', 'cyclistenoir', 'Moyen', array['athleisure','TikTok'], 277),
  ('Shorts', 'ShortDeVille', 'shortdeville', 'Faible à moyen', array['lookbook','quotidien'], 278),
  ('Shorts', 'ShortCargoFemme', 'shortcargofemme', 'Moyen', array['streetstyle','TikTok'], 279),
  ('Shorts', 'ShortImprimé', 'shortimprime', 'Faible à moyen', array['été','lookbook'], 280),
  ('Manteaux', 'ManteauFemme', 'manteaufemme', 'Élevé', array['lookbook','quotidien'], 281),
  ('Manteaux', 'TrenchFemme', 'trenchfemme', 'Élevé', array['mi-saison','lookbook'], 282),
  ('Manteaux', 'ManteauOversize', 'manteauoversize', 'Moyen', array['lookbook','streetstyle'], 283),
  ('Manteaux', 'ManteauLaine', 'manteaulaine', 'Moyen', array['hiver','quotidien'], 284),
  ('Manteaux', 'ManteauCamel', 'manteaucamel', 'Moyen', array['lookbook','quotidien'], 285),
  ('Manteaux', 'ManteauNoir', 'manteaunoir', 'Élevé', array['quotidien','lookbook'], 286),
  ('Manteaux', 'DoudouneFemme', 'doudounefemme', 'Élevé', array['hiver','quotidien'], 287),
  ('Manteaux', 'DoudouneOversize', 'doudouneoversize', 'Moyen', array['streetstyle','TikTok'], 288),
  ('Vestes', 'VesteEnCuirFemme', 'vesteencuirfemme', 'Élevé', array['lookbook','soirée'], 289),
  ('Vestes', 'VesteJeansFemme', 'vestejeansfemme', 'Élevé', array['casual','lookbook'], 290),
  ('Vestes', 'VesteBomber', 'vestebomber', 'Moyen', array['streetstyle','quotidien'], 291),
  ('Vestes', 'VesteMatelassée', 'vestematelassee', 'Moyen', array['mi-saison','quotidien'], 292),
  ('Blazers', 'BlazerFemme', 'blazerfemme', 'Élevé', array['bureau','lookbook'], 293),
  ('Blazers', 'BlazerOversize', 'blazeroversize', 'Élevé', array['streetstyle','lookbook'], 294),
  ('Blazers', 'BlazerCroisé', 'blazercroise', 'Moyen', array['bureau','lookbook'], 295),
  ('Blazers', 'BlazerVintage', 'blazervintage', 'Moyen', array['seconde main','lookbook'], 296),
  ('Blazers', 'BlazerColoré', 'blazercolore', 'Moyen', array['lookbook','TikTok'], 297),
  ('Blazers', 'BlazerLin', 'blazerlin', 'Faible à moyen', array['été','lookbook'], 298),
  ('Blazers', 'BlazerRayé', 'blazerraye', 'Faible à moyen', array['bureau','lookbook'], 299),
  ('Blazers', 'BlazerSecondeMain', 'blazersecondemain', 'Faible à moyen', array['sustainable','quotidien'], 300),
  ('Chaussures', 'ChaussuresFemme', 'chaussuresfemme', 'Élevé', array['lookbook','détail'], 301),
  ('Chaussures', 'EscarpinsFemme', 'escarpinsfemme', 'Moyen', array['soirée','évènement'], 302),
  ('Chaussures', 'TalonsFemme', 'talonsfemme', 'Élevé', array['soirée','lookbook'], 303),
  ('Chaussures', 'SandalesFemme', 'sandalesfemme', 'Élevé', array['été','quotidien'], 304),
  ('Chaussures', 'MulesFemme', 'mulesfemme', 'Moyen', array['été','lookbook'], 305),
  ('Chaussures', 'BallerinesFemme', 'ballerinesfemme', 'Moyen', array['quotidien','tendance'], 306),
  ('Chaussures', 'MaryJaneFemme', 'maryjanefemme', 'Moyen', array['niche','tendance'], 307),
  ('Chaussures', 'BottesFemme', 'bottesfemme', 'Élevé', array['automne','hiver'], 308),
  ('Chaussures', 'BottinesFemme', 'bottinesfemme', 'Élevé', array['automne','lookbook'], 309),
  ('Chaussures', 'CuissardesFemme', 'cuissardesfemme', 'Moyen', array['soirée','éditorial'], 310),
  ('Sneakers', 'SneakersFemme', 'sneakersfemme', 'Très élevé', array['streetstyle','quotidien'], 311),
  ('Sneakers', 'DadSneakers', 'dadsneakers', 'Moyen', array['streetstyle','TikTok'], 312),
  ('Sneakers', 'ChunkySneakers', 'chunkysneakers', 'Moyen', array['lookbook','streetstyle'], 313),
  ('Sneakers', 'SneakersBlanches', 'sneakersblanches', 'Élevé', array['quotidien','lookbook'], 314),
  ('Sneakers', 'SneakersVintage', 'sneakersvintage', 'Moyen', array['seconde main'], 315),
  ('Sneakers', 'RunningLifestyle', 'runninglifestyle', 'Moyen', array['athleisure','quotidien'], 316),
  ('Sneakers', 'SneakersColorées', 'sneakerscolorees', 'Moyen', array['TikTok','lookbook'], 317),
  ('Sneakers', 'SneakersPlatform', 'sneakersplatform', 'Faible à moyen', array['niche','lookbook'], 318),
  ('Sneakers', 'SneakersSecondeMain', 'sneakerssecondemain', 'Faible à moyen', array['sustainable'], 319),
  ('Sneakers', 'CustomSneakers', 'customsneakers', 'Moyen', array['créa','TikTok'], 320),
  ('Sacs', 'SacFemme', 'sacfemme', 'Élevé', array['lookbook','détail'], 321),
  ('Sacs', 'SacDuJour', 'sacdujour', 'Moyen', array['quotidien','reels'], 322),
  ('Sacs', 'SacBandoulière', 'sacbandouliere', 'Moyen', array['quotidien','pratique'], 323),
  ('Sacs', 'SacÉpaule', 'sacepaule', 'Moyen', array['lookbook','quotidien'], 324),
  ('Sacs', 'SacBaguette', 'sacbaguette', 'Moyen', array['Y2K','TikTok'], 325),
  ('Sacs', 'SacCameraBag', 'saccamerabag', 'Faible à moyen', array['niche'], 326),
  ('Sacs', 'MiniSac', 'minisac', 'Moyen', array['soirée','lookbook'], 327),
  ('Sacs', 'ToteBagFemme', 'totebagfemme', 'Élevé', array['quotidien','écolo'], 328),
  ('Sacs', 'SacEnRaphia', 'sacenraphia', 'Moyen', array['été','vacances'], 329),
  ('Sacs', 'SacEnCuir', 'sacencuir', 'Élevé', array['lookbook','premium'], 330),
  ('Sacs', 'SacSecondeMain', 'sacsecondemain', 'Moyen', array['sustainable','Segna'], 331),
  ('Sacs', 'SacVintage', 'sacvintage', 'Élevé', array['seconde main'], 332),
  ('Sacs', 'SacDeLuxe', 'sacdeluxe', 'Élevé', array['luxe','investissement'], 333),
  ('Sacs', 'PochetteSoirée', 'pochettesoiree', 'Moyen', array['évènement','mariage'], 334),
  ('Sacs', 'SacBananeFemme', 'sacbananefemme', 'Moyen', array['streetstyle','TikTok'], 335),
  ('Sacs', 'SacCeinture', 'sacceinture', 'Faible à moyen', array['niche'], 336),
  ('Sacs', 'SacStructuré', 'sacstructure', 'Faible à moyen', array['lookbook','bureau'], 337),
  ('Sacs', 'SacMousseline', 'sacmousseline', 'Faible à moyen', array['niche','éditorial'], 338),
  ('Sacs', 'PortefeuilleFemme', 'portefeuillefemme', 'Faible à moyen', array['détail produit'], 339),
  ('Sacs', 'PortecarteFemme', 'portecartefemme', 'Faible à moyen', array['détail produit'], 340),
  ('Maille', 'PullFemme', 'pullfemme', 'Élevé', array['quotidien','lookbook'], 341),
  ('Maille', 'PullOversize', 'pulloversize', 'Élevé', array['cosy','TikTok'], 342),
  ('Maille', 'PullColRoulé', 'pullcolroule', 'Moyen', array['hiver','bureau'], 343),
  ('Maille', 'CardiganFemme', 'cardiganfemme', 'Élevé', array['quotidien','layering'], 344),
  ('Maille', 'CardiganOversize', 'cardiganoversize', 'Moyen', array['lookbook','cosy'], 345),
  ('Maille', 'GiletMaille', 'giletmaille', 'Moyen', array['mi-saison','quotidien'], 346),
  ('Maille', 'PullEnCachemire', 'pullencachemire', 'Moyen', array['premium','capsule'], 347),
  ('Maille', 'PullColV', 'pullcolv', 'Moyen', array['bureau','quotidien'], 348),
  ('Maille', 'PullRayé', 'pullraye', 'Moyen', array['lookbook','French vibe'], 349),
  ('Maille', 'PullTricot', 'pulltricot', 'Moyen', array['hiver','cosy'], 350),
  ('Maille', 'PullVintage', 'pullvintage', 'Moyen', array['seconde main'], 351),
  ('Maille', 'PullChandail', 'pullchandail', 'Faible à moyen', array['niche','hiver'], 352),
  ('Maille', 'PullCropped', 'pullcropped', 'Moyen', array['TikTok','layering'], 353),
  ('Maille', 'PullColoré', 'pullcolore', 'Moyen', array['tendance','lookbook'], 354),
  ('Maille', 'PullNoir', 'pullnoir', 'Moyen', array['basique','quotidien'], 355),
  ('Maille', 'PullBlanc', 'pullblanc', 'Moyen', array['basique','capsule'], 356),
  ('Maille', 'PullSecondeMain', 'pullsecondemain', 'Faible à moyen', array['sustainable'], 357),
  ('Maille', 'CardiganVintage', 'cardiganvintage', 'Moyen', array['seconde main'], 358),
  ('Maille', 'PullPointes', 'pullpointes', 'Faible à moyen', array['éditorial'], 359),
  ('Maille', 'PullTexturé', 'pulltexture', 'Faible à moyen', array['détail produit'], 360),
  ('Accessoires', 'CeintureFemme', 'ceinturefemme', 'Moyen', array['détail','lookbook'], 361),
  ('Accessoires', 'CeintureTaille', 'ceinturetaille', 'Faible à moyen', array['silhouette','niche'], 362),
  ('Accessoires', 'ChapeauFemme', 'chapeaufemme', 'Moyen', array['été','éditorial'], 363),
  ('Accessoires', 'BobFemme', 'bobfemme', 'Moyen', array['streetstyle','TikTok'], 364),
  ('Accessoires', 'CasquetteFemme', 'casquettefemme', 'Moyen', array['casual','sport'], 365),
  ('Accessoires', 'FoulardFemme', 'foulardfemme', 'Moyen', array['détail','lookbook'], 366),
  ('Accessoires', 'LunettesDeSoleilFemme', 'lunettesdesoleilfemme', 'Élevé', array['été','détail'], 367),
  ('Accessoires', 'CollantsFemme', 'collantsfemme', 'Moyen', array['automne','hiver'], 368),
  ('Accessoires', 'CollantsFantaisie', 'collantsfantaisie', 'Faible à moyen', array['niche','éditorial'], 369),
  ('Bijoux', 'BijouxFemme', 'bijouxfemme', 'Élevé', array['détail','gros plan'], 370),
  ('Bijoux', 'CollierFemme', 'collierfemme', 'Élevé', array['détail','reels'], 371),
  ('Bijoux', 'BouclesDOreilles', 'bouclesdoreilles', 'Élevé', array['détail','close-up'], 372),
  ('Bijoux', 'BraceletsFemme', 'braceletsfemme', 'Moyen', array['détail','quotidien'], 373),
  ('Bijoux', 'BaguesFemme', 'baguesfemme', 'Élevé', array['macro','TikTok'], 374),
  ('Bijoux', 'BijouxPerles', 'bijouxperles', 'Moyen', array['coquette','romantique'], 375),
  ('Bijoux', 'BijouxVintage', 'bijouxvintage', 'Moyen', array['seconde main'], 376),
  ('Bijoux', 'BijouxMinimalistes', 'bijouxminimalistes', 'Moyen', array['capsule','quotidien'], 377),
  ('Bijoux', 'BijouxDorés', 'bijouxdores', 'Moyen', array['soirée','lookbook'], 378),
  ('Bijoux', 'BijouxArgentés', 'bijouxargentes', 'Moyen', array['quotidien','lookbook'], 379),
  ('Bijoux', 'BijouxSecondeMain', 'bijouxsecondemain', 'Faible à moyen', array['sustainable'], 380)
on conflict (slug) do update set
  category = excluded.category,
  label = excluded.label,
  reach_tier = excluded.reach_tier,
  relevance_contexts = excluded.relevance_contexts,
  sort_order = excluded.sort_order,
  is_active = true;

